services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./state.json:/app/state.json
    command: streamlit run src/app.py --server.address 0.0.0.0 --server.port 8501

  ingestion:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./state.json:/app/state.json
    command: python -u src/main.py
    profiles:
      - jobs
