services:
  - type: web
    name: docs-assistant-ui
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.web
    dockerCommand: sh -c "streamlit run src/app.py --server.address 0.0.0.0 --server.port ${PORT:-8501}"
    envVars:
      - key: BASE_URL
        value: https://support.optisigns.com
      - key: LOCALE
        value: en-us
      - key: MAX_ARTICLES
        value: 30
      - key: GEMINI_API_KEY
        sync: false
      - key: FILE_SEARCH_STORE_NAME
        sync: false

  - type: cron
    name: docs-ingestion-daily
    runtime: docker
    schedule: "45 5 * * *"
    dockerfilePath: ./Dockerfile
    dockerCommand: python -u src/main.py
    envVars:
      - key: BASE_URL
        value: https://support.optisigns.com
      - key: LOCALE
        value: en-us
      - key: MAX_ARTICLES
        value: 30
      - key: GEMINI_API_KEY
        sync: false
      - key: FILE_SEARCH_STORE_NAME
        sync: false
